signalwire/freeswitch

src/mod/applications/mod_av/avcodec.c, src/mod/applications/mod_av/avformat.c
Should fix crashes mentioned in #25
=> [mod_av] Fix crash on `av show codecs` and `av show formats`.

README.md
=> Updated slack community link to the current (working) join link as old one expired. Closes #29

src/mod/endpoints/mod_sofia/sofia_glue.c, src/mod/endpoints/mod_sofia/sofia_reg.c
=> [mod_sofia] Fix some incorrect word contractions.

src/mod/event_handlers/mod_kazoo/kazoo_ei_config.c, src/mod/event_handlers/mod_kazoo/mod_kazoo.c
* also reverts event_stream_framing default value
=> [mod_kazoo] missing call to kz_set_hostname

src/switch_core_sqldb.c
core_event_handler uses sql_manager which was not fully initiated by the time events may start go through
=> [Core] Fix wrong sqldb initialization order causing crash on load.

src/mod/applications/mod_av/avformat.c
[mod_av] fix mod_av not have auido when use avresample.
=> [mod_av] Fix mod_av not having audio when using avresample

src/mod/event_handlers/mod_kazoo/kazoo_commands.c, src/mod/event_handlers/mod_kazoo/kazoo_ei.h, src/mod/event_handlers/mod_kazoo/kazoo_ei_config.c, src/mod/event_handlers/mod_kazoo/kazoo_ei_utils.c, src/mod/event_handlers/mod_kazoo/kazoo_fetch_agent.c, src/mod/event_handlers/mod_kazoo/kazoo_node.c, src/mod/event_handlers/mod_kazoo/mod_kazoo.c
* fixes several potential memory leaks
* formatting
* fixes parameter name
* logs unsupported parameters
=> [mod_kazoo] Fix potential memory leaks

docs/phrase/phrase_de.xml, docs/phrase/phrase_en.xml
phrase_de.xml now contains a corresponding German phrase for every phrase in phrase_en.xml
Fix some duplicate, empty, or conflicting definitions in phrase_en.xml
=> [docs/phrase] Translated all phrases (voice prompts) to German. 

src/switch_cpp.cpp, src/switch_rtp.c
Turn DTMF logging on or off using sensitive_dtmf channel variable for PCI compliance.
=> [core] Turn DTMF logging on or off using sensitive_dtmf var

src/mod/applications/mod_conference/conference_event.c
On branch issue_210
Changes to be committed:
modified:   src/mod/applications/mod_conference/conference_event.c
=> [mod_conference] Fix possible NULL argument.

src/mod/event_handlers/mod_kazoo/Makefile.am, src/mod/event_handlers/mod_kazoo/kazoo.conf.xml, src/mod/event_handlers/mod_kazoo/kazoo_api.c, src/mod/event_handlers/mod_kazoo/kazoo_cdr.c, src/mod/event_handlers/mod_kazoo/kazoo_commands.c, src/mod/event_handlers/mod_kazoo/kazoo_config.c, src/mod/event_handlers/mod_kazoo/kazoo_dptools.c, src/mod/event_handlers/mod_kazoo/kazoo_ei_config.c, src/mod/event_handlers/mod_kazoo/kazoo_ei_utils.c, src/mod/event_handlers/mod_kazoo/kazoo_endpoints.c, src/mod/event_handlers/mod_kazoo/kazoo_event_stream.c, src/mod/event_handlers/mod_kazoo/kazoo_fetch_agent.c, src/mod/event_handlers/mod_kazoo/kazoo_fields.h, src/mod/event_handlers/mod_kazoo/kazoo_message.c, src/mod/event_handlers/mod_kazoo/kazoo_node.c, src/mod/event_handlers/mod_kazoo/kazoo_tweaks.c, src/mod/event_handlers/mod_kazoo/kazoo_utils.c, src/mod/event_handlers/mod_kazoo/kazoo_utils.h, src/mod/event_handlers/mod_kazoo/mod_kazoo.c, src/mod/event_handlers/mod_kazoo/mod_kazoo.h
* scan-build warnings
* loglevel per event
* serialize as-array
* verbose fields
* kz_cdr
=> [mod_kazoo] some fixes & enhancements

src/mod/event_handlers/mod_kazoo/kazoo_dptools.c, src/mod/event_handlers/mod_kazoo/kazoo_ei.h, src/mod/event_handlers/mod_kazoo/kazoo_ei_config.c, src/mod/event_handlers/mod_kazoo/kazoo_ei_utils.c, src/mod/event_handlers/mod_kazoo/kazoo_node.c
- add configured sleep time between each io fault
- add configured delay before fetching initial configuration
- add explicit handling of http_cache for kz_moh
=> [mod_kazoo] maintenance

.gitconfig
Signed-off-by: Stefan Weil <sw@weilnetz.de>
=> Add git configuration to ignore errors from `git fsck`

src/mod/applications/mod_av/avcodec.c
The video is very rough when the con-current call is increased. The code change break packets evenly for the video.
=> [mod_av] Break packets evenly

src/mod/applications/mod_spandsp/Makefile.am, src/mod/endpoints/mod_gsmopen/Makefile.am
Hi all,
Two fixes. One for a simple typo and the other for mod_gsmopen which hasn't been updated yet.
Kind regards,
Seb
=> [mod_spandsp, mod_gsmopen] Fix typo and build with external spandsp

src/include/switch_apr.h, src/mod/event_handlers/mod_event_socket/mod_event_socket.c, src/mod/event_handlers/mod_rayo/xmpp_streams.c, src/switch_msrp.c
Enables MSRP listening over IPv6, including dual stack binding.
=> [core] Enable MSRP over IPv6

src/switch_ivr.c
Correct multiple instances where the XML node offsets were set improperly.
=> [Core] Fix XML generation

src/mod/applications/mod_http_cache/aws.c
Must have been a bad merge. An Include is there multiple times
=> [mod_http_cache] Remove duplicate include statements

freeswitch.spec
Please check to commit comments for details.
=> [Build-System] freeswitch.spec update

src/mod/endpoints/mod_sofia/sofia.c, src/mod/endpoints/mod_sofia/sofia_glue.c
so it's easy to relate session id and sip call-id
=> [mod_sofia] add call-id to log line to link with session uuid

src/mod/languages/mod_python/mod_python.c
* [mod_python.c] eval_some_python: fix leaks for python objects.
=> [mod_python] Fix PyObject leaks in eval_some_python function

src/mod/endpoints/mod_sofia/sofia.c
https://github.com/signalwire/freeswitch/issues/1033
=> Verification of the wss.pem certificate in mod_sofia application code. Display correct reason why sofia profile failed to create

src/include/switch.h, src/include/test/switch_test.h, tests/unit/Makefile.am, tests/unit/switch_console.c, tests/unit/switch_core_db.c, tests/unit/switch_core_video.c, tests/unit/switch_event.c, tests/unit/switch_hash.c, tests/unit/switch_ivr_originate.c, tests/unit/switch_rtp.c, tests/unit/switch_utils.c, tests/unit/switch_vad.c, tests/unit/switch_vpx.c
Signed-off-by: s3rj1k <evasive.gyron@gmail.com>
=> [Unit-tests] Fix previously defined AM_* in tests.

src/switch_rtp.c
This helps us debug what happend when rtp sending might fail.
=> [core] add log debug socket sendto

src/mod/applications/mod_conference/mod_conference.c
=> [mod_conference] Bridged conference did not wait it's last member before destroy and crashed.

src/mod/endpoints/mod_sofia/sofia.c
issue: https://github.com/signalwire/freeswitch/issues/1245
=> [mod_sofia] Fixed a few Usage-of-uninitialized value bugs which may cause information discolsure and bypass ACL check

src/mod/event_handlers/mod_rayo/mod_rayo.c
fixes  #704 - mod_rayo returns error on exec_conference_api
=> [mod_rayo] mod_rayo returns error exec_conference_api

scripts/debian_min_build.sh
See commit b29174e and e43b192.
=> [Build-System] Add libswscale-dev debian package to the debian_min_build.sh

src/mod/applications/mod_av/avcodec.c
=> [mod_av] FIX parse config param "profile" and "level"

src/mod/event_handlers/mod_json_cdr/conf/autoload_configs/json_cdr.conf.xml, src/mod/event_handlers/mod_json_cdr/mod_json_cdr.c
=> [mod_json_cdr] add timeout param.

src/switch_rtp.c
(fix proposed by Leon de Rooij)
=> [core] Handling RTCP MUX resulting in gaps

docker/master/Dockerfile
ITNOA
This issue resolved #1586 and merge from #1364 
**My work**
* I updated your branch to head of master.
* I correct keyserver
* I persist gpg key in layer
=> [Docker] Correct keyserver and key id in the Dockerfile

docker/master/Dockerfile
ITNOA
As you can see in `docker/master/Dockerfile`, we have two RUN immediately, that I think it is not necessary and making extra layer, so I remove it.
This PR resolved #1588
=> [Docker] Fix broken gpg --verify and Dockerfile cleanup

src/switch_core_asr.c
=> [core] fix memory leak in switch_core_asr_feed

src/mod/applications/mod_test/test/test_tts.c
… tts_time function of the unit-test.
=> [mod_test] Increase tts_time unit-test's duration window.

src/mod/applications/mod_commands/mod_commands.c
* fixed memory leak
* added custom delimeter support
* fixed return value
=> [mod_commands] Fix and improve coalesce function

src/mod/applications/mod_callcenter/mod_callcenter.c
Fixes these issues:
#1148 
#1973
=> [mod_callcenter] Fix stale agents and UUID broadcasts

src/include/switch_curl.h, src/mod/applications/mod_curl/mod_curl.c, src/mod/applications/mod_httapi/mod_httapi.c, src/mod/applications/mod_http_cache/azure.c, src/mod/applications/mod_http_cache/mod_http_cache.c, src/switch_curl.c
https://github.com/curl/curl/commit/6967571bf20624bc4cfa68fb8f90cbc53a87c6f2
=> [Core, mod_curl, mod_httapi, mod_http_cache] Compatible with libcurl>=7.87.0

src/include/switch_curl.h, src/mod/applications/mod_curl/mod_curl.c, src/mod/applications/mod_httapi/mod_httapi.c, src/mod/applications/mod_http_cache/azure.c, src/mod/applications/mod_http_cache/mod_http_cache.c, src/switch_curl.c
This reverts commit 039823848906b11fd6183ba81f037b7211a29497.
=> Revert "[Core, mod_curl, mod_httapi, mod_http_cache] Compatible with libcurl>=7.87.0"

src/switch_apr.c, src/switch_core_cert.c, src/switch_rtp.c
Low-level openssl api for accessing md5 was deprecated in openssl3.0, leading to errors during compile of freeswitch. 
Update switch_md5 method to use the openssl high-level api. 
syntax plagiarized from: 
https://stackoverflow.com/questions/69806220/advice-needed-for-migration-of-low-level-openssl-api-to-high-level-openssl-apis
=> [Core] OpenSSL 3 support

src/switch_rtp.c
This fixes https://github.com/signalwire/freeswitch/issues/2195
From OpenSSL 3 docs for [SSL_CTX_set0_tmp_dh_pkey](https://www.openssl.org/docs/man3.0/man3/SSL_CTX_set0_tmp_dh_pkey.html):
`Applications may supply their own DH parameters instead of using the built-in values. This approach is discouraged and applications should in preference use the built-in parameter support described above. Applications wishing to supply their own DH parameters should call SSL_CTX_set0_tmp_dh_pkey() or SSL_set0_tmp_dh_pkey() to supply the parameters for the SSL_CTX or SSL respectively. The parameters should be supplied in the dhpkey argument as an EVP_PKEY containing DH parameters. Ownership of the dhpkey value is passed to the SSL_CTX or SSL object as a result of this call, and so the caller should not …
=> [core] Use auto DH params with openssl3

src/mod/endpoints/mod_verto/mod_verto.c
resolves [1553](https://github.com/signalwire/freeswitch/issues/1553)
=> [mod_verto] Add context into msg event header

README.md, docker/README.md
Hi.  I noticed that mailing list link on the main README.md redirects readers to the list sign-up page, but the list has been archived.  It also attempts to update the ports documentation in docker/README.md
=> misc readme updates

src/switch_time.c
=> [Core] softtimer: fix crash in timezones when reloading xml

debian/util.sh
This is needed for GHA workflow, adding ability to prep source bundle without actually resetting git history or building source tars and the actual debs.
Function splitting is done in such a way, that it preserves all previous UX from CLI invocation, add add two more functions, so general flow would look like this:
```
VERSION=$(cat ./build/next-release.txt)
HASH=$(echo ${GITHUB_SHA} | cut -c1-10)
./debian/util.sh prep-create-orig -n -v${VERSION}-${{ env.GITHUB_RUN_NUMBER }}~${HASH}
./debian/util.sh prep-create-dsc ${{ matrix.codename }}
...
```
=> [build] Split `create_dsc` and `create-orig` functions in `util.sh`.

src/mod/formats/mod_vlc/mod_vlc.c
Resolves the following issue: https://github.com/signalwire/freeswitch/issues/2433
=> [mod_vlc] Resolve double mutex lock

debian/util.sh
This will generate `freeswitch_*.orig.tar.xz` files that have same hash across all build targets in scope of same workflow run.
=> [UTIL] Generate reproducible source archive.

scripts/setup-git.sh
Show the email section when the email has changed instead of when the name has changed in the git setup script.
=> [Scripts] Only show email changed section if it was changed

src/mod/applications/mod_curl/mod_curl.c
=> [mod_curl] Fix off-by-one error in argument limit checks.
