signalwire/freeswitch

libs/libzrtp/include/zrtp_config.h

The Elbrus architecture (aka E2K, aka 2000) is LE.
Signed-off-by: Andrew Savchenko <bircoph@altlinux.org>

Add support for the Elbrus architecture

---

src/mod/event_handlers/mod_event_multicast/mod_event_multicast.c

Taken from FS-11193:
In "event_handler()" function, when encrypting data using openssl 1.1.0,
the context ctx is allocated by "EVP_CIPHER_CTX_new()", then data is
encrypted, and at the end, EVP_CIPHER_CTX_cleanup is called. This
function resets the context (the function itself is deprecated, and has
been renamed to "EVP_CIPHER_CTX_reset) so that it can be used again. The
correct call would be to "EVP_CIPHER_CTX_free()", which frees the
memory. The code for openssl 1.0 is OK, since the "ctx" struct is kept
in stack.  The same thing happens during decryption. "ctx" is allocated,
but never freed.
Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

[mod_event_multicast] Fix memory leak

---

libs/esl/fs_cli.c

Related to FS-11309.
Commit bc3e1c9e7de1855eec454bba467fd2586e5e251b introduced a typo that
results in EL_REFRESH never being used, even if available. This can
cause the screen to garble.
This fixes the typo.
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

[fs_cli] Fix typo, resolves garbled screen

---

conf/vanilla/autoload_configs/msrp.conf.xml
src/include/switch_msrp.h
src/switch_msrp.c

MSRP is enabled by default; this PR implements a configuration option so the default behaviour can be changed when desired.
Also addresses signalwire/freeswitch#22

Disable MSRP option

---

src/mod/event_handlers/mod_amqp/mod_amqp_connection.c

The `heartbeat` connection parameter of `amqp.conf` is not currently parsed properly.
This PR also partially addresses #59 (the other subissues to be handled by different PRs)

[mod_amqp] Properly parse out heartbeat parameter

---

src/mod/endpoints/mod_sofia/sofia.c

used by sip tracing tools and not to confuse with application (X-) or (P-)

[mod_sofia] add K- to prefixes that create a sip_h_ variable

---

conf/vanilla/autoload_configs/amqp.conf.xml
src/mod/event_handlers/mod_amqp/mod_amqp.h
src/mod/event_handlers/mod_amqp/mod_amqp_command.c

The current code base creates the commands queue in auto-delete mode by default; in addition, other available [queue properties](https://www.rabbitmq.com/amqp-0-9-1-reference.html#class.queue) are also hardcoded.
This PR exposes the said properties via module's configuration file, while retaining backwards compatibility by defaulting the values so they match the previous behaviour.
This PR partly addresses #68

[mod_amqp] configurable commands queue properties

---

src/mod/event_handlers/mod_amqp/mod_amqp_logging.c
src/mod/event_handlers/mod_amqp/mod_amqp_producer.c

For the logging and the producer queues, the connections are open both in their respective threads as well as during the profile initialization. This PR removes the latter attempt as it is redundant as well as it prevents the configured profiles from ever attempting to reconnect, as described in #59
Please note the command queue is not affected by the behaviour described in the ticket as it was already tweaked a while back (commit https://github.com/signalwire/freeswitch/commit/ba63cc45744ddc45ee24961ddf348044821830eb)

[mod_amqp] open logging and produced connections from within their threads

---

src/mod/applications/mod_callcenter/mod_callcenter.c

Ref: https://freeswitch.org/jira/browse/FS-11094
When you load mod_callcenter and there is an issue with the configuration, it doesn't allow you to reload it a second time, this is caused before we reserve the `callcenter::info` event before loading the module successfully.
Here some of the error logs when this is occurring:
> 2018-04-05 06:44:46.614437 [ERR] mod_callcenter.c:4140 Couldn't register subclass callcenter::info!
> 2018-04-05 06:44:46.614437 [CRIT] switch_loadable_module.c:1522 Error Loading module /usr/lib/freeswitch/mod/mod_callcenter.so
*Module load routine returned an error*
To easily reproduce you can put an error in your odbc settings, the load mod_callcenter, after it fails you will not be able to load it again.

[mod_callcenter] Unreserve callcenter events when config errors loading

---

src/mod/event_handlers/mod_event_socket/mod_event_socket.c

Avoids crash described on issue #21 due to null socket dereferencing on `switch_socket_opt_set()` call.  However, the root cause of why the socket `listener->sock` is null is not clear yet.

adds null pointer checks on listener session and socket

---

src/mod/applications/mod_callcenter/mod_callcenter.c

Adding SAF_SUPPORT_NOMEDIA to callcenter_track since we don't need media up for it. 
Also, a small fix to make it compile on OSX.

[mod_callcenter] Adding SAF_SUPPORT_NOMEDIA to callcenter_track since we don't need media up for it. Also, a small fix to make it compile on OSX.

---

src/include/switch_xml.h

Commit 7907994 introduced a copy/paste mistake that may result in
compile failure:
In file included from ../../../../src/include/switch.h:134,
from mod_xml_ldap.c:34:
mod_xml_ldap.c: In function 'xml_ldap_search':
../../../../src/include/switch_xml.h:236:68: error: implicit declaration of function 'switch_xml_toxml_buf'; did you mean 'switch_xml_toxml_buf_ex'? [-Werror=implicit-function-declaration]
#define switch_xml_toxml_buf(xml, buf, buflen, offset, prn_header) switch_xml_toxml_buf(xml, buf, buflen, offset, prn_header, USE_UTF_8_ENCODING);
^~~~~~~~~~~~~~~~~~~~
mod_xml_ldap.c:764:9: note: in expansion of macro 'switch_xml_toxml_buf'
switch_xml_toxml_buf(xml, buf, 0, 0, 1);
^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[7]: *** [Makefile:710: …

[core] Fix copy/paste mistake in switch_xml.h

---

configure.ac

Upstream libs for ubuntu seem to provide only mariadb.pc and not libmariadb.pc - simple fallback check gets the build working.

[Build-system] Fallback for mariadb lib check

---

src/switch_loadable_module.c

[Core] switch_loadable_module wrongly logs that modules.conf loading fails while it's pre_load_modules.conf

---

src/mod/endpoints/mod_portaudio/mod_portaudio.c

Fixes https://github.com/signalwire/freeswitch/issues/169

[mod_portaudio] CF_AUDIO flag is not set

---

src/mod/event_handlers/mod_kazoo/kazoo_dptools.c
src/mod/event_handlers/mod_kazoo/kazoo_ei.h
src/mod/event_handlers/mod_kazoo/kazoo_ei_config.c
src/mod/event_handlers/mod_kazoo/kazoo_ei_utils.c
src/mod/event_handlers/mod_kazoo/kazoo_event_stream.c
src/mod/event_handlers/mod_kazoo/kazoo_node.c

* implements ei_queue_pop that calls
switch_queue_trypop or switch_queue_pop_timeout
depending on timeout value
* default for `sender_timeout` is set to 0
to bring back previous behaviour of
using `switch_queue_trypop` when fetching
messages to be sent to erlang node
this PR closes #260

[mod_kazoo] queue timeout configuration

---

libs/spandsp/src/t4_tx.c

Scan-build should be happier with this.

[SpanDSP] Remove unused x_repeats variable from header_row_read_handler()

---

src/mod/applications/mod_conference/conference_video.c

It looks like allocating it on the Heap  makes Asan give more info: "READ of size 16424 at 0x629000050200 thread T50"

[mod_conference] fix overflow (video mode == passthrough)

---

src/switch_cpp.cpp
src/switch_event.c
src/switch_time.c

Reduce log level to DEBUG for binding to events and certain clock messages.
The purpose of these changes are only to reduce logging when set to a log level other than DEBUG.  
The clock logging change is based more on the actual text (removing "I am FREE after all") and there would already be a CRITICAL message prior to the message which I have switched to use DEBUG level.
For example: When clock adjustment made on FreeSWITCH server:
2019-11-07 12:47:08.718054 [CRIT] switch_time.c:1151 Reverse Clock Skew Detected!
2019-11-07 12:47:08.718054 [DEBUG] switch_time.c:1164 If you see this message many times consider a nicer machine to run me on.

[core] Reduce log level to DEBUG for some functions

---

src/switch_core_file.c

This PR attempts to fix the issue when a small part of a file should be played but almost nothing gets played instead.
The issue can be reproduced with the following steps:
1. create a conference
2. play a low bitrate file with a small timeout eg. conference test play {timeout=1800}sound.vox
[sound.zip](https://github.com/signalwire/freeswitch/files/4041022/sound.zip)
Problem:
If file buffer is considerably bigger than max_samples than keeping track of samples read instead of samples returned might result in a significantly shorter play
My fix:
increment fh->samples in only with the amount actually returned from each switch_core_file_read invocation

[core] fix: don't terminate file before max_samples returned

---

debian/control-modules

debian buster contains libhiredis0.14.
for now u have to install libhiredis0.13 or 0.10 from old repo to install mod-hiredis on debian 10

[mod_hiredis] Fix dependency for Debian Buster.

---

conf/vanilla/autoload_configs/httapi.conf.xml
src/mod/applications/mod_httapi/conf/autoload_configs/httapi.conf.xml
src/mod/applications/mod_httapi/docs/mod_httapi_doc.txt
src/mod/applications/mod_httapi/mod_httapi.c

Added a new param for mod_httapi, which will limit the time taken to establish connection to the server.
Current default timeout (i.e. 300 seconds) is too high.

[mod_httapi] Introduction of connect-timeout param

---

src/switch_rtp.c

See [Issue 467: STUN Binding Request verification truncates username & fails](https://github.com/signalwire/freeswitch/issues/467)

[Core] switch_rtp: update username to allow size specified in STUN RFC 5389

---

src/mod/formats/mod_vlc/mod_vlc.c

Access to field 'pool' results in a dereference of a null pointer (loaded from variable 'acontext')

[mod_vlc] scan-build: Access to field 'context' results in a dereference of a null pointer (loaded from variable 'tech_pvt');

---

src/mod/endpoints/mod_verto/mod_verto.c

According to mod_sofia, when a leg receives a cmd replace the first leg get transfer_disposition variable equals recv_replace and this step is missing on mod_verto
[mod_verto]: Setting transfer_disposition to recv_replace on aleg for command replace handler (attended transfer)
[mod_verto]: Setting transfer_disposition to recv_replace on aleg for command replace handler (blind transfer)

[mod_verto] Setting transfer_disposition to recv_replace on aleg

---

src/mod/endpoints/mod_portaudio/mod_portaudio.c

Value stored to 'codec_ms' is never read.

[mod_portaudio] scan-build: Access to field 'next' results in a dereference of a null pointer (loaded from variable 'previous').

---

src/mod/event_handlers/mod_kazoo/kazoo_commands.c
src/mod/event_handlers/mod_kazoo/kazoo_dptools.c
src/mod/event_handlers/mod_kazoo/kazoo_ei_utils.c
src/mod/event_handlers/mod_kazoo/kazoo_tweaks.c

- add kz_eval api
works by expanding channel variables and not event
- use session if available in first-of
- handle bridge variables maintenance
- allow some time for erlang node to fully initialize
- add kz_moh
tries to start moh from earlier UNHOLD position

[mod_kazoo] maintenance

---

src/mod/endpoints/mod_sofia/mod_sofia.h
src/mod/endpoints/mod_sofia/sofia.c
src/mod/endpoints/mod_sofia/sofia_reg.c

As defined here https://docs.microsoft.com/en-us/microsoftteams/direct-routing-sbc-multiple-tenants, Teams Direct Routing requires the 'Contact' header to exist on OPTIONS ping messages.
This code change was actually proposed and tested successfully by Shaun Stokes here: https://lists.freeswitch.org/pipermail/freeswitch-users/2019-August/132225.html and https://freeswitch.org/jira/projects/FS/issues/FS-11978. 
The code introduces a new gateway param called 'contact-in-ping'.

[mod_sofia] Add new gateway param 'contact-in-ping' to support for Microsoft Teams Direct Routing

---

conf/vanilla/sip_profiles/external.xml
conf/vanilla/sip_profiles/internal.xml

<param name="ext-sip-ip" value="$${external_rtp_ip}"/>  in files internal.xml and external.xml,but it maybe is $${external_sip_ip}

[Configuration] sip_profiles: Use $${external_sip_ip} for ext-sip-ip, $${external_rtp_ip} for ext-rtp-ip

---

src/mod/endpoints/mod_sofia/sofia.c

The index counter check for maximum configuration entries was swapped by mistake.

[mod_sofia] Fix rtp config ipv4/ipv6 index confusion

---

src/mod/codecs/mod_silk/mod_silk.c

Hi, I try enable mod_silk in FS and find SILK always has maxaveragebitrate=20000, it cause from the `switch_silk_fmtp_parse()` will seek maxaveragebitrate according the `codec_fmtp.actual_samples_per_second` but it's 0. 
The solution is, init the `actual_samples_per_second before` before calling `switch_silk_fmtp_parse()`. 
Please review the changes. Thanks.

[mod_silk] Fix mod_silk always init with maxaveragebitrate=20000

---

src/mod/codecs/mod_amr/mod_amr.c
src/mod/codecs/mod_amrwb/mod_amrwb.c

RFC4867 says:
If a mode set was supplied in the offer, the answerer SHALL return the mode-set unmodified or reject the payload type
FS was replying with its own default mode-set even if it was offered one. This causes interoperability issues.

[mod_amr, mod_amrwb] RFC4867 mode-set compliancy

---

src/mod/applications/mod_cv/mod_cv.cpp

Access to field 'shape_scale' results in a dereference of a null pointer.
Dead assignments.

[mod_cv] scan-build: Null pointer passed as an argument to a 'nonnull' parameter.

---

libs/esl/fs_cli.c

"miliseconds" to "milliseconds"

[esl] Fix typo in fs_cli.c

---

src/mod/codecs/mod_silk/mod_silk.c

Hi,
The return code from `switch_jb_peek_frame()` is `SWITCH_STATUS_SUCCESS(0)` or `SWITCH_STATUS_FALSE(1)`, it's incorrectly used in `switch_silk_decode()`. 
Please review and commit this change, thanks.

[mod_silk] switch_silk_decode: Fix invalid condition for return code from switch_jb_peek_frame().

---

src/mod/endpoints/mod_sofia/sofia.c

FS crashes when proxies INFO without a body.
In sip_profile parameter `proxy-info=true`
Example of INFO sent via sipp
```
INFO sip:STAS@127.0.0.1:11000;transport=UDP SIP/2.0
Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
Route: <sip:192.168.0.34:5063;lr>
From: sipp <sip:sipp@[local_ip]:[local_port]>;tag=[pid]SIPpTag00[call_number]
To: [service] <sip:[service]@[remote_ip]:[remote_port]>[peer_tag_param]
Call-ID: [call_id]
CSeq: 2 INFO
Contact: sip:sipp@[local_ip]:[local_port]
Max-Forwards: 70
```

[mod_sofia] Fix crash when proxy INFO without body

---

src/mod/formats/mod_opusfile/Makefile.am

fix #718 : honor $OPUSFILE_ENCODE_CFLAGS and -DHAVE_OPUSFILE_ENCODE when compiling mod_opusfile.c

[mod_opusfile] fix compiling write file support

---

src/mod/endpoints/mod_sofia/sofia.c

From FS-11833.
After FS sends a reINVITE to T38 which gets rejected by peer it is no
longer in a state where it can properly answer a reINVITE which requests
a change of the media setup.
1. FS sends INVITE (destination is a fax machine)
2. Call connects with "8 101"
3. FS sends reINVITE to T38
4. T38 rejected (488)
5. FS receives INVITE to "8"
6. FS replies with 200 OK without SDP
7. Call fails
The bug is related to TFLAG_SDP. This flag is set when a media session
is established. And when there's a reINVITE sofia_glue_do_invite() from
sofia_glue.c is called and clears the flag again:
`sofia_clear_flag_locked(tech_pvt, TFLAG_SDP);`
So when FS sends a reINVITE to T38 the flag gets cleared. But when the
reINVITE is rejected with 488 the flag is not set again. It stays
cleared. So the call …

[mod-sofia] Fix reINVITE after T38 is rejected

---

freeswitch.spec

[Build-System] Relocate modules deps in freeswitch.spec

---

src/mod/event_handlers/mod_rayo/iks_helpers.h

Addresses #742 with proper references to XMPP errors, previously declared via macros in [iks_helpers.c](https://github.com/signalwire/freeswitch/blob/master/src/mod/event_handlers/mod_rayo/iks_helpers.c#L34-L38)

[mod_rayo] Enable -fno-common compilation

---

src/switch_utils.c
tests/unit/switch_utils.c

switch_b64_decode returns truncated value issue:
When `encode` "ABC" and `decode` back with a 4 bytes buffer, the value will be truncated to "AB" and the test case fails.
chk_eq_str: 'AB' != 'ABC'
This patch fix it, and changed to return length not included the NULL char.

[Core] Fix the null char in truncated value returned by switch_b64_decode

---

src/switch_core_cert.c

following the advice from
https://bugs.chromium.org/p/chromium/issues/detail?id=1123946#c12
since boringssl in recent versions enforces x509v3 certificates
when using extensions like subjectAltName

[Core] Create x509v3 certificates

---

src/include/switch_core.h
src/switch_core_cert.c
src/switch_core_media.c

This PR performs a couple of validation actions against the key/certificate pair used for DTLS/SRTP, including a test against key's cryptographic length to make sure it will be regenerated if its length is less than 4096 bits.

[core] DTLS PEM validation/creation tweaks and fix leaks in fixed pem path.

---

w32/openssl.props

[Core] Enable use of DTLSv1_2 on Windows.

---

libs/apr/network_io/unix/multicast.c

Fixes #859, essentially replicating the fix from the [upstream](https://svn.apache.org/viewvc?view=revision&revision=493802); the issue manifests on BSDs/mac with disabled IPv6.

[apr] fix find_if_index for BSDs/mac

---

src/mod/endpoints/mod_sofia/sofia.c

Adding in sip_identity value from the sofia library into the sip_i_identity channel variable

[mod_sofia] Add back sip Identity header into  sip_i_identity variables in sofia_parse_all_invite_headers

---

src/switch_core_media.c

Seven years ago, commit cb076e6 used xor as pow. The compiler Clang 10
errors about this copy-paste-error from RFC 5245 section 4.1.2.1. Now,
Clang compiles successfully.

[core] Fix ICE candidate priorities

---

src/switch_core_media.c

Fix [switch_core_media.c]: Store correct value in srtp_remote_audio_crypto_key channel variable

[Core] switch_core_media: Correct srtp_remote_audio_crypto_key variable

---

src/mod/applications/mod_av/Makefile.am

Five years ago, commit b29174e added the scale/conversion library of
FFmpeg. However, that library is not part of libavformat-dev and added
an additional requirement. That was not reflected in the error message,
when FFmpeg libraries are missing.

[mod_av] Update error message

---

src/mod/applications/mod_spandsp/udptl.c

Seven years ago, commit eee96c6 introduced two white-space errors. The
compiler Clang 10 errors: misleading indentation; statement is not
part of the previous 'if'. Now, Clang compiles successfully.

[mod_spandsp] Fix two white-space errors

---

src/include/switch_platform.h

musl 1.2 defaults to 64-bit time_t, causing a compile failure under 32-bit platforms.

[build] fix compilation under musl 1.2

---

src/switch_core_sqldb.c

Fixes following error.
PostgreSQL:
```
Query (create index recovery3 on recovery(runtime_uuid)) returned PGRES_FATAL_ERROR
```
MySQL/MariaDB
```
(create index recovery3 on recovery(runtime_uuid)) to database: Duplicate key name 'recovery3'
```
Replicate:
- Load `mod_pgsql` or `mod_mariadb`
- Set `core-db-dsn` in `switch.conf.xml` to use postgresql,  odbc or mariadb.
- Set `auto-create-schemas` to `true` (Default)

[Core] Databases: Fix duplicate key name 'recovery3'

---

src/mod/codecs/mod_opus/mod_opus.c

Had this issue back in October with a specific Chrome version. When there's packet loss from the browser (tested with 10% using Linux netem (tc qdisc add dev ethx root netem loss 10%) and VMware fusion) mod_opus fails to decode the samples and return SWITCH_STATUS_FALSE and this makes switch_core_media hangup the call, changing to SWITCH_STATUS_NOOP fixed the issue and there's no, apparently, audio issues.
With latest chrome stable and canary I couldn't reproduce the issue anymore.

[mod_opus] Do not hangup call on decode error - fix 86a5ee3509

---

src/mod/languages/mod_v8/mod_v8.cpp

mod_v8.cpp: In function ‘switch_status_t process_status_function(const char*, switch_core_session_t*, switch_stream_handle_t*)’:
mod_v8.cpp:1245:52: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
char *as = NULL, *output_text = NULL, *delim = ",";
^~~
mod_v8.cpp:1263:8: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
as = "plain";
^~~~~~~

[mod_v8] Fix C++ compile warning

---

src/mod/applications/mod_httapi/mod_httapi.c

log message copied from file-cache-ttl variable
[abs-file-cache-ttl message](https://github.com/signalwire/freeswitch/blob/master/src/mod/applications/mod_httapi/mod_httapi.c#L1741) is a copy of [file-cache-ttl message](https://github.com/signalwire/freeswitch/blob/master/src/mod/applications/mod_httapi/mod_httapi.c#L1733)

[mod_httpapi] Fix abs-file-cache-ttl typo

---

src/mod/say/mod_say_en/mod_say_en.c
src/mod/say/mod_say_es_ar/mod_say_es_ar.c
src/mod/say/mod_say_he/mod_say_he.c
src/mod/say/mod_say_sv/mod_say_sv.c

Hi,
The macro `say_num` will return but didn't free the memory in `say_ip()` function. This PR try to fix the possible memory leak.
Regards
Lin

[mod_say_*] fix possible memory-leak in say_ip()

---

conf/vanilla/sip_profiles/external.xml

Previously, the configuration file vars.xml set the TLS Cipher Suites only for internal SIP profiles. External SIP profiles used the 'DEFAULT' set of the underlying OpenSSL. Now, external SIP profiles copy to the general setting of vars.xml as well. Of course, you can overwrite this anytime, for example, to use different sets for internal and external.

[configuration] Copy TLS ciphers from vars.xml even in Vanilla External

---

src/switch.c
w32/switch_version.props

Enabled `FreeSwitchConsole -version` opt which worked in the Linux version but not in the Windows build
`PS D:\dev\freeswitch\ruccfsfork> .\FreeSwitchConsole.exe -version`
Will output:
```
FreeSWITCH version: 1.10.3-release~ca04fc3104~64bit (ca04fc3104 64bit)
```
or
```
FreeSWITCH version: 1.10.3-dev-4560~ca04fc3104~64bit (ca04fc3104 64bit)
```

[FreeSwitchConsole] -version option enabled in windows + read git revision

---

src/mod/applications/mod_av/avformat.c

fix mod_av record crash bug
it will lead ffmpeg-4.1\libavformat\utils.c(4424): if (s->url) {
av_freep(&s->url);
}
this time freep will dump.
recommit after seven du tutorial, thank you for that

[mod_av] Fix record crash bug

---

src/mod/endpoints/mod_sofia/sofia.c

This PR removes the "precondition" option from Supported: header when 100rel mode is enabled, addressing #904 
comparing RFC3312 and the freeswitch codebase, I see no support for the mechanisms that "precondition" is intended to support (eg. `a=des, a=curr`), in my opinion it makes sense to remove it until such a time that rfc3312 is supported
In more concrete terms - freeswitch (or it's included modules) do not maintain a precondition table which is a "MUST" for  RFC3312 "precondition" functionality (there are probably other unsatisfied MUSTs, that's just the first one I've found: https://tools.ietf.org/html/rfc3312#section-5.1)

[mod_sofia] Remove 'precondition' from 'Supported:' w/ 100rel

---

src/mod/xml_int/mod_xml_curl/conf/autoload_configs/xml_curl.conf.xml
src/mod/xml_int/mod_xml_curl/mod_xml_curl.c

[mod_xml_curl] Allow XML_CURL_MAX_BYTES to be configured at runtime per-binding. 
* Added "response-max-bytes" config param for mod_xml_curl
* XML_CURL_MAX_BYTES define still used as default if param omitted
* Added example configuration to module example config.

[mod_xml_curl] Allow XML_CURL_MAX_BYTES to be configured at runtime 

---

src/switch_dso.c

Modified to capture return value of 2nd call to LoadLibraryEx and added a third call to widen the search to the module.

[Core] Capture return value of 2nd call to LoadLibraryEx and add a third call to widen the search to the module in switch_dso_open().

---

src/mod/applications/mod_enum/mod_enum.c

```Direct leak of 504 byte(s) in 3 object(s) allocated from:
#0 0x7f9d9cf2fd28 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1d28)
#1 0x7f9d8e2775ca in ldns_resolver_new (/usr/lib/x86_64-linux-gnu/libldns.so.2+0x395ca)
#2 0x7f9d8e4b9d23 in enum_lookup /root/github/freeswitch/src/mod/applications/mod_enum/mod_enum.c:626
#3 0x7f9d8e4b9ff0 in enum_dialplan_hunt /root/github/freeswitch/src/mod/applications/mod_enum/mod_enum.c:647
#4 0x7f9d9be2857f in switch_core_standard_on_routing src/switch_core_state_machine.c:282
#5 0x7f9d9be2857f in switch_core_session_run src/switch_core_state_machine.c:644
#6 0x7f9d9be1a78c in switch_core_session_thread src/switch_core_session.c:1709
#7 0x7f9d9be105e8 in switch_core_session_thread_pool_worker src/switch_core_session.c:1772
#8 0x7f9d9c4ebc4a in …
```

[mod_enum] fix mem leak - ldns_resolver_new() - vanilla cfg.

---

src/switch_rtp.c

Five years ago, commit 8e1b2ea enabled ECDHE for the DTLS server by hard-coding P-256. Released before that, OpenSSL 1.0.2, allows auto selection of the curve (P-256, P-384, and P-512). OpenSSL 1.1.x has this enabled on default, which adds groups/curves like X25519 and X448 automatically. This change here allows DTLS clients with a demand for Security Level 4 (192 bit) and Level 5 (256 bit) connecting to the DTLS server.

[core] Allow other (D)TLS Curves/Groups beside P-256

---

libs/esl/python/python-config
src/mod/applications/mod_avmd/mod_avmd.c

Adds 2 small fixups for building `mod_avmd` and `esl/python` with current build tooling from Fedora 32.

[mod_avmd, esl/python] Two build fixups

---

scripts/gentls_cert.in

Debian Buster updated /etc/ssl/openssl.cnf to default to
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
gentls_cert currently uses SHA1 as message digest. According to OpenSSL
documentation this only offers 80 bit of security. 80 bits is enough for
security level 1, but not 2.
The OpenSSL default MD nowadays is SHA256. This commit updates
gentls_cert to use it.
Issue was reported on the FS mailing list. The certificates created by
gentls_cert caused "md too weak" errors and clients were unable to
connect.
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

[gentls_cert] Update message digest

---

src/switch_rtp.c

Warning message about missed packets is misleading.
Message indicates greater (>) however, the conditional is greater than or equals (>=).
The message prints the value of rtp_sesstion->missed_count twice instead of printing the value of rtp_session->max_missed_packets.

[Core] switch_rtp: fix switch_rtp_set_max_missed_packets logging

---

src/mod/applications/mod_commands/Makefile.am

Please consider linking mod_commands tests against a noinst library for better cross platform compatibility.
This is the approach taken by many other modules such as endpoints/mod_sofia, applications/mod_conference, languages/mod_lua etc.

[mod_commands] OpenBSD compat

---

src/mod/applications/mod_http_cache/aws.c

Addresses https://github.com/signalwire/freeswitch/issues/1280
In certain random but valid conditions (  date and aws key dependent )  we found scenarios where the call to `zstr(key)`  would return true and thus result in empty querystring in our AWS S3 puts.
Here is a sample portion of the evidence ( note that the logging of key_bytes ) was our own interim troubleshooting.  Note the `00` 
```
2021-07-23 19:37:09.126912 [INFO] aws.c:52 key_bytes: 
2021-07-23 19:37:09.126912 [INFO] aws.c:52 00
2021-07-23 19:37:09.126912 [INFO] aws.c:52 3f
```

[mod_http_cache] Fix the query string not included for HTTP PUT requests to s3

---

src/include/switch_utils.h
tests/unit/switch_core.c

Add following 2 utility functions in switch_utils.h:
- static inline long int switch_safe_atol(const char *nptr, long int dft)
- static inline long long int switch_safe_atoll(const char *nptr, long long int dft)

[Core] Add switch_safe_atol() and switch_safe_atoll() functions. Add a unit-test.

---

src/mod/applications/mod_dptools/mod_dptools.c

This is a fix for the issue mentioned [here](https://github.com/signalwire/freeswitch/issues/1332).

[mod_dptools] Fix silence_ms misspelling typo in vad_test command

---

src/mod/formats/mod_opusfile/mod_opusfile.c

Since the last round of changes it fails to compile:
```
mod_opusfile.c: In function 'decode_stream_cb':
mod_opusfile.c:933:143: error: format '%lx' expects argument of type 'long unsigned int', but argument 8 has type 'switch_thread_id_t' {aka 'struct __pthread *'} [-Werror=format=]
933 |                 switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_DEBUG, "[OGG/OPUS Stream Decode] decode_stream_cb(): switch_thread_self(): %lx\n",  switch_thread_self());
|                                                                                                                                             ~~^      ~~~~~~~~~~~~~~~~~~~~
|                                                                                                                                               |      |
| …
```

[mod_opusfile] fix type errors

---

src/switch_core_video.c
tests/unit/switch_core_video.c

Recent changes made it impossible to compile freeswitch without libyuv
support.
src/switch_core_video.c: In function 'switch_img_read_from_file':
src/switch_core_video.c:3139:4: error: implicit declaration of function 'RAWToI420' [-Werror=implicit-function-declaration]
RAWToI420(data, width * 3,
^
src/switch_core_video.c:3148:4: error: implicit declaration of function 'ABGRToARGB' [-Werror=implicit-function-declaration]
ABGRToARGB(data, width * 4, img->planes[SWITCH_PLANE_PACKED], img->stride[SWITCH_PLANE_PACKED], width, height);
^
Fix this my adding/moving the checks for "SWITCH_HAVE_YUV".
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

[core] fix "--disable-libyuv"

---

src/mod/endpoints/mod_sofia/sofia_reg.c

SHA-512/256 was not offered because OPENSSL_VERSION_NUMBER was not defined in sofia_reg.c

[mod_sofia] Fix regression in RFC-8760.

---

src/mod/formats/mod_opusfile/mod_opusfile.c

not draining before destroying encoder causes loss at the end of the encoded file

[mod_opusfile] add opc_encoder_drain before destroying handle

---

src/mod/applications/mod_distributor/mod_distributor.c

PR for #1217 the reload message of distributor should be same as others

[mod_distributor] Reload message should be same as others (+OK instead of +ok)

---

src/mod/event_handlers/mod_amqp/mod_amqp_command.c
src/mod/event_handlers/mod_amqp/mod_amqp_utils.c

Found queueName leak here.
https://github.com/signalwire/freeswitch/blob/f3604557e52ff14ae98f7f5080472ba2543ef1ac/src/mod/event_handlers/mod_amqp/mod_amqp_command.c#L368

[mod_amqp] Fix memory leaks on command queue name and parsing configure file

---

configure.ac
src/include/switch_private.h.cmake

since 380fd060ef719b1d8f8781422e84d2a32066351d, execinfo.h is not used
anymore, so there is no need to check for it.

[build] skip checking unused execinfo.h

---

src/mod/endpoints/mod_sofia/mod_sofia.c

Autocompletion suggest only *reg* argument to see all registrations on profile, while exist 
*pres* (search registrations by presence_hosts) and *user* (search by username) commands.
In help this command listed correctly:
```<status|xmlstatus> profile <name> [reg [<contact str>]] | [pres <pres str>] | [user <user@domain>]```

[mod_sofia] Add autocomplete options to status profile command

---

src/switch_core_cert.c

https://github.com/signalwire/freeswitch/issues/1461
https://github.com/signalwire/libks/commit/3493e9c952964c80e402aa0497891d57dc5f8d40

[core] fix macOS build when missing CRYPTO_mem_ctrl

---

src/mod/applications/mod_voicemail/mod_voicemail.c

Fix #1135 - Consider the presence of a hash as equivalent to the presence of a password when evaluating the allow-empty-password-auth option.

[mod_voicemail] Fix voicemail ignoring vm-a1-hash

---

src/mod/endpoints/mod_sofia/mod_sofia.c

When a failed registration was waiting for a retry, we couldn't see the time left when doing sofia status for example.  I've also changed the > to >= because when it about to retry, it would say NEVER instead of 0.
More work is needed around it, like adding limit in the retry time that being created.
I haven't confirmed, but at some point FS would crash if the number of failure become big enough :
gateway_ptr->failures++;
AND
sec = gateway_ptr->retry_seconds * gateway_ptr->failures;
Those 2 could get to be problematic at some point.
But this patch wouldn't affect the issue mentioned.  So I'm not combining the fix for the other one in this.

[mod_sofia] Provide retry time for failed and waiting registration

---

src/mod/endpoints/mod_sofia/sofia_glue.c

Some DID providers want Caller ID name in contact for 911 or other emergency calls and some wont allow outbound at all untill this is set

[mod_sofia] Caller ID name in contact

---

src/include/switch_module_interfaces.h
src/switch_ivr_play_say.c

This add support to specify volume="-10" in phrase action
the switch_file_handle only supported the ->vol flag which have a total of 8 volume correction position.
So I've added the ->volgranular which is based on the switch_resample code which is similar to the ->vol, but provide 100 volume setting in a much larger range of value.

[core] Add support to phrase play-file to set a volume attribute

---

src/switch_ivr_async.c

Hi,
This PR sets recording completion cause for failures that previously did not have cause set.
Without this, it's impossible from CHANNEL_EXECUTE_COMPLETE event to distinguish if `record_session` ended without failure or did not even start because of failure.
I tested it and it worked fine. Thank you.

[core] set completion cause upon failed recording

---

src/mod/applications/mod_conference/conference_file.c

Issue  #1119
Solution: don't even start to play file if conference is not running.

[mod_conference] file descriptor stays open

---

src/mod/endpoints/mod_sofia/sofia_presence.c

After rejecting the subscription for authentication the function calls goto end. In the end block freeswitch fires PRESENCE_PROBE events and releases the allocated memory
* when rejecting a call for auth PRESENCE_PROBE should not get fired
* This caused all other subscribers to the same entity to get flooded with NOTIFY's because `call_id` only gets set later in the function, so when firing the PRESENCE_PROBE without `call_id` being set all subscriptions will get a notify
* this can be considered a security flaw as any unauthorized user can send
SUBSCRIBES and trigger thousands of NOTIFY's to the SUBSCRIBED endpoints
This was fixed simply my moving down the end label after the code that
sends the PRESENCE_PROBE event

[mod_sofia] Fix PRESENCE_PROBE firing on rejection

---

src/mod/applications/mod_callcenter/mod_callcenter.c

`globals` was getting initialized to null after `switch_event_bind_removable` binding causing `globals.nodes` to get set to NULL causing `switch_event_unbind` not to be able to unbind the `SWITCH_EVENT_PRESENCE_PROBE` event when unloading the module. Besides not being able to unbind the event, this was also causing a segfault  upon receiving a `PRESENCE_PROBE` event when unloading or reloading the module

[mod_callcenter] Fix SWITCH_EVENT_PRESENCE_PROBE unbind

---

src/mod/formats/mod_shout/Makefile.am

Space indent will cause a error when running ./configure when HAVE_MP3LAME is false.

[mod_shout] Replace space with tab in Makefile.am

---

src/mod/loggers/mod_logfile/mod_logfile.c

this prevents a scenario where freeswitch.log fails to get rotated and eventually fills up the hard drive causing a crash. See issue #1738

[mod_logfile] Continue renaming if a logfile doesn't exist

---

src/mod/endpoints/mod_sofia/mod_sofia.c

This allows a channel variable to force display update support for unsupported user agents. 
Example: We have a new mobile app that has a user-agent that is not currently in the freeswitch code to send display updates in situations such as call park pickup. 
We add to our dialplan 
```	
<condition field="${sip_user_agent}" expression="NewSoftphone">
<action application="set" data="update_ignore_ua=true"/>
</condition>
```
Benefit: 
This has the huge benefit of not requiring a re-compile of freeswitch for every user agent we want to support for display update, we can simply handle new supported user agents in our applications or dialplans.

[mod_sofia] Ignore user agent for display update when channel variable update_ignore_ua is true

---

src/switch_rtp.c

Wrong buffer size (and larger than the available memory size, 513 instead of 256) is passed when filling luser_ice in snprintf.
If ICE type is other than ICE_VANILLA then luser_ice buffer is unitialized when it is passed to strdup. I've filled it with empty string here, but I'm not sure if this is functionally correct for all the cases.

[Core] ICE: fix wrong buffer size being passed and unitialized buffer

---

src/mod/event_handlers/mod_amqp/mod_amqp.h
src/mod/event_handlers/mod_amqp/mod_amqp_producer.c

Adds support to subscribe to CUSTOM events with specific subclasses by using the `event_filter` with ^ as a delimiter between the event and the subclass.
example:
```xml
<param name="event_filter" value="SWITCH_EVENT_CUSTOM^sofia::register" />
```

[mod_amqp] Event subclass support

---

src/mod/event_handlers/mod_event_multicast/mod_event_multicast.c

The important one might be related to derefencing invalid pointer (crashing) when specific message is received (example: ":" followed by MAGIC and followed by some filler).
I've attached simple Win32 tool to reproduce this. It is pre-filled by default with multicast address - this worked in my test with Linux FS, but for Windows I had to use unicast address. I have not investigated it further yet, it might be my local issue.
Same tool can be used to trigger another issue, related to empty UDP packet being received (https://github.com/signalwire/freeswitch/issues/1884).
[Win32 UdpSender.zip](https://github.com/signalwire/freeswitch/files/10144236/UdpSender.zip)

[mod_event_multicast] Few fixes

---

src/mod/endpoints/mod_sofia/sofia.c
src/mod/endpoints/mod_sofia/sofia_presence.c
src/mod/endpoints/mod_sofia/sofia_reg.c

In FS-6400, the attempt was made to randomize OPTIONS
packets to be sent at a random interval.  The same random
interval is applied to all endpoints so this doesn't work.
Furthermore, rounding withing the code will ultimately
make the ping times converge over time.
This commmit will apply the random interval only during
registration of the endpoint.  All subsequent pings will
be incremented with the actual value of ping-mean-interval.
Fixes #1132, Fixes #1133

[mod_sofia] Randomize OPTIONS Ping interval

---

src/mod/applications/mod_cidlookup/mod_cidlookup.c
src/switch_xml_config.c

In mod_cidlookup and several other modules, config parameters
are read from external XML files using the SWITCH_CONFIG_ITEM_STRING_STRDUP
method.  These items do not have string_options, and are not freed
with switch_xml_config_cleanup.  We therefore need to call switch_safe_free
for config without string_options.  We also add switch_xml_config_cleanup
to mod_cidlookup.  There are other modules that may be affected but this
commit makes no attempt at fixing those.
Fixes #1752

[core, mod_cidlookup] Free memory allocated via strdup

---

src/mod/applications/mod_ladspa/mod_ladspa.c

Without these -- especially activate() -- stateful plugins will not be set up correctly.
For example, the low-pass filter "lpf" in the CMT library may produce a pop when starting since its state is not zeroed out.
Fixes #1899

[mod_ladspa] Added activate/deactivate support.

---

src/mod/formats/mod_png/mod_png.c

During a conference call, a PNG file is played using the api:
`conference <conf-name> play {full-screen=true,png_ms=-1}/assets/image.png`
While this is active the conference participants experience choppy audio.
1 - FS skipping RTP timestamps in the member output streams.
2 - Because main conference thread was taking too long to acquire the `conference->file_mutex` at the end of its loop.
3 - `conference->file_mutex` was being locked by the conference muxing thread.
4 - conference muxing thread was trying to read a frame from the PNG file being played.
5 - Code typo in mod_png caused a "blocked" read to occur.

[mod_png] Fix unexpected png video blocked read

---

src/switch_core_media.c

This PR reverts https://github.com/signalwire/freeswitch/commit/c61d89a47fc793475aa7ef97b39c58d266284889
and fixes the lock order.

[Core] Fix possible deadlock in switch_core_media_set_codec()

---

scripts/lua/hangup_jitterbuffer_metrics.lua
src/include/switch_jitterbuffer.h
src/include/switch_types.h
src/mod/codecs/mod_opus/Makefile.am
src/mod/codecs/mod_opus/mod_opus.c
src/mod/codecs/mod_opus/opus_parse.c
src/mod/codecs/mod_opus/opus_parse.h
src/switch_jitterbuffer.c
src/switch_rtp.c

We have been using the jitter buffer of freeswitch (audio only) with some webrtc users, it works fine, but I noticed it was not accelerating/shrinking, unless facing a jitter buffer reset.
Once we noticed that, we decided to cap to maximum size to 120ms. (Some users were complaining about excessive delay.)
While looking at the WebRTC jitter buffer stats, I noticed it was sometimes reaching a size of 300ms and more.
I decided to implement an acceleration algorithm, here is how it works:
Every time the jitter buffer it getting a packet with `jb_next_packet_by_seq()` (Support for the timestamp mode was not added yet).
it will compare the current estimated jitter and the current size of the jitter buffer, if the jitter buffer is 3x the estimate jitter, it is too large and we need to …

[core, mod_opus] more elastic jitterbuffer expand/accelerate when using Opus codec.

---

src/mod/databases/mod_mariadb/mod_mariadb.c

Fix DeadLock. https://github.com/signalwire/freeswitch/issues/2063
If the message "Deadlock found when trying to get lock; try restarting transaction" is specified, then 100 attempts are made to retry the SQL request.
If all attempts fail, the message "DeadLock. The retries are over." is displayed in the logs.

[mod_mariadb] Fix "DeadLock. The retries are over." message.

---

src/switch_console.c

Fix in switch_console.c file.
Adds column names when inserting data.
Calls to use the complete table in Galera Multi-Master Cluster

[Core] Fix switch_console.c for Galera Mariadb cluster

---

docker/master/Dockerfile

Hi, I'm not 100% sure what context(s) this Dockerfile is used in, but it appeared to be the right starting place for building images based on the package in the SignalWire repo.  The goals of the PR:
- default to Debian bookworm
- drop the dependency on `lsb-release` since `DEBIAN_VERSION` is supplied as an ARG (although `lsb-release` has gotten much smaller starting in bookworm)
- use Debian's [gosu](https://tracker.debian.org/pkg/gosu) package; it is available since at least buster
- add a `FS_META_PACKAGE` build-arg to make it easy to build other meta package-based variants
- add the `-c` argument to `SHELL`;  without this, a docker build `RUN` using this image as a base would fail with an exec error
I've tested building and running several variants like so:
``` sh
docker build …
```

updates for the Debian Dockerfile

---

src/mod/applications/mod_conference/conference_loop.c

The conference output loop accesses the member's read_impl while resampling. The output loop also spawns off the input loop thread, which is where the member->read_impl is actually initialised. This results in an uncommon race where the output loop sometimes gets an uninitialised member->read_impl and bails with logs something like this:
```
2023-10-12 18:19:01.436844 [DEBUG] conference_loop.c:1340 Setup timer soft success interval: 20  samples: 960 from codec L16
2023-10-12 18:19:01.436844 [DEBUG] conference_loop.c:1497 Outbound conference channel answered, setting CFLAG_ANSWERED
2023-10-12 18:19:01.436844 [NOTICE] switch_core_media.c:15852 Activating write resampler
2023-10-12 18:19:01.436844 [DEBUG] switch_core_media.c:16097 Engaging Write Buffer at 1920 bytes to accommodate 0->1920 …
```

[mod_conference] Avoid a race in member->read_impl access

---

docker/master/Dockerfile

On several installs on recent Debian and Ubuntu systems, I have noticed that GID 999 is already allocated on the system running the container, making it a minor hassle to share a common freeswitch UID and GID between the Docker host and the container.
The conflicting group id varies, but is typically either one of the systemd groups or polkitd, which are dynamically created when those packages are installed.  The behavior stems from the range of system GIDs being between 100-999 ([see Debian Policy 9.2.2](https://www.debian.org/doc/debian-policy/ch-opersys.html#uid-and-gid-classes)) and the fact that system installation dynamically allocates from this range.  I didn't track down exactly why these daemons are allocating from the top of the range, since the default behavior of `adduser` and …

[Docker] Change default freeswitch UID and GID to 499 in docker/master/Dockerfile

---

src/mod/event_handlers/mod_amqp/mod_amqp_command.c

Refined Logging Level for FreeSWITCH's mod_amqp: The logging level for the AMQP module in FreeSWITCH has been updated from 'warning' to 'debug'. This adjustment ensures a more suitable level for the log message and eliminates any potential impact on production environments. Previously, the 'warning' level would lead to unnecessary log entries for each individual message, although there was no actual warning condition. This change improves logging efficiency and appropriateness for mod_amqp's operations within FreeSWITCH.

[mod_amqp] Adjusting to Appropriate Log Level for Message

---

src/mod/event_handlers/mod_event_socket/mod_event_socket.c

This fixes a possibility for MAX_MISSED to be exceeded if more logs are attempted to be pushed to the listener's queue after running kill_listener but before the listener thread gets CPU time and removes itself.
On a heavily loaded system with a lot of logs in the event dispatch queue these excessive logs may prove fatal since socket_logger itself will produce logs about the full queue, resulting in a circular situation of never-ending logs.
The same logic was applied to event_handler after finding the same behaviour mentioned in signalwire/freeswitch#2143.

[mod_event_socket] Check if listener is running before pushing more logs or events to its queue

---

Freeswitch.2017.sln
src/mod/codecs/mod_opus/mod_opus.c
tests/unit/switch_core_codec.c
tests/unit/test_switch_core_codec.2017.vcxproj

This PR reverts the change made by https://github.com/signalwire/freeswitch/pull/982

[mod_opus] Fix status returned by switch_opus_decode(). Should be SWITCH_STATUS_FALSE instead of SWITCH_STATUS_NOOP. Add a unit-test.

---

src/mod/endpoints/mod_verto/mod_verto.c

For mod_verto regex was never freed and was actually leaking memory. Correctly free the compiled regex to fix the memory leak.

[mod_verto] Fix memory leak by correctly freeing regex

---

src/mod/endpoints/mod_sofia/sofia.c

Added missing %s in contact header format string when formatting with rfc_5626, extension number and IPv6.

[mod_sofia] Added missing %s in one form of contact string

---

configure.ac
libs/libvpx/build/make/configure.sh

this is the same patch as in https://github.com/signalwire/freeswitch/pull/1956 which was accidentally deleted.
It works for me on the latest macOS as of today.

[Build-System] Fix build for m1 and m2 chips on macOS

---

src/mod/databases/mod_pgsql/mod_pgsql.c

Extend the database module to handle the PGRES_TUPLES_CHUNK case introduced in PostgreSQL 17. This ensures compatibility with the latest PostgreSQL version and prevents potential issues when processing query results.

[mod_pgsql] Add support for PGRES_TUPLES_CHUNK in PostgreSQL 17+

---

src/mod/applications/mod_curl/mod_curl.c

Introduced a macro `MOD_CURL_MAX_ARGS` for the number of arguments for mod_curl functions with a default of 30. Adjusted the code to handle scenarios exceeding this limit by logging an error and returning failure. This improves flexibility and prevents potential overflow issues.

[mod_curl] Increase argument limit and enforce max args constraint

---

src/mod/languages/mod_lua/freeswitch.i
src/mod/languages/mod_lua/freeswitch_lua.cpp
src/mod/languages/mod_lua/freeswitch_lua.h
src/mod/languages/mod_lua/hack.diff
src/mod/languages/mod_lua/mod_lua_wrap.cpp

The added method, query_rows, allows the retrieval of rows from a database without the need for a callback function, it fetches the rows and returns 3 arguments as show below.
```lua
local success, rows, err = dbh:query_rows(sql)
```
This function performs better with large number of rows. Test results below 50k rows returned.
dbh:query(sql, callback) - 0.335949 seconds
dbh:query_rows(sql) - 0.253178 seconds

[mod_lua] Add Dbh:query_rows

---

src/mod/timers/mod_timerfd/mod_timerfd.c

When taking a snapshot of a machine which pauses the process, mod_timerfd runtime thread exits, causing all channels to wait indefinitely.
Check `errno == EINTR` and continue the timer loop.

[mod_timerfd] Fixed - continue timer loop after receiving a SIGSTOP

---

src/mod/databases/mod_pgsql/mod_pgsql.c

New function, `void pgsql_handle_set_error_if_not_set(switch_pgsql_handle_t *handle, char **err)` has been added to mod_pgsql module. This function is now called at several points where an error occurred but *err was not yet set.

[mod_pgsql] err is now set correctly (dbh:last_error())

---

src/mod/endpoints/mod_sofia/mod_sofia.c
src/mod/endpoints/mod_sofia/sofia.c
src/mod/endpoints/mod_sofia/sofia_presence.c
src/mod/endpoints/mod_sofia/sofia_reg.c

We observed that the new Poly phones (formerly known as Polycom) were not getting sent a SIP UPDATE in certain circumstances (example: retrieving a parked call, and therefore, Caller ID would not show the parked caller). I renamed Polycom to Poly which will catch all Poly AND Polycom UA's. I also added Acrobits, and Ringotel to extend such functionality to those UA's. There were also other minor compatibility issues with the new Poly phones which have been resolved with tweaking the UA recognition on the code.

[mod_sofia] Update Polycom UA to recognize new Poly phones

---

src/mod/formats/mod_shout/mod_shout.c

fix error: ignoring return value of function declared with warn_unused_result attribute [-Werror,-Wunused-result] Apple clang version 15.0.0 (clang-1500.1.0.2.5)

[mod_shout] fix build with new clang on macOS

---

src/mod/applications/mod_spandsp/mod_spandsp.c
src/mod/applications/mod_spandsp/mod_spandsp.h
src/mod/applications/mod_spandsp/mod_spandsp_dsp.c

This patch from my colleague allows FreeSWITCH to compile with latest or earlier spandsp code base:
spandsp, beginning with commit d9681c37 and coinciding with the SPANDSP_RELEASE_DATE of 20230620, introduced the following changes to its V.18 protocol API, which FreeSWITCH is not able to compile against:
- Certain V.18 constants were renamed.
- The v18_init function now requires passing a third function, handling the V.18 modem's status changes.
This patch allows FreeSWITCH to build against current versions of spandsp by:
- Using the new V.18 constant names.
- Implementing a simple status reporter callback function and passing it as the third function to v18_init.
Additionally, it retains backward compatibility with prior versions of spandp through #if conditions checking the value of …

[mod_spandsp] Fix compilation against >=2023/06/02 spandsp

---

.github/workflows/macos.yml

Tested on empty Mac Intel and Apple Silicon. Both failed due to missing pkgconf. It is required and not auto downloaded as prerequisite to other packages.
Note the name is now pkgconf on homebrew. It is the newer version of pkg-config and pkgconfig which are now aliases that point to pkgconf on homebrew.
ref: https://github.com/MarioG-X/freeswitch/pull/2

[GHA] Add pkgconf to macos.yml

---

configure.ac

This PR changes configure.ac (_removed from PR: target libraries for Apple Silicon computers_) and a general cleanup/update for macOS. Apple has stated that other programs should be installed into /opt (/opt/freeswitch) for Apple Silicon computers instead of /usr/local. Homebrew installs everything in /opt.  
_NOTE the following change for the target was removed from the PR per developers:
Added code to auto change the default prefix from /usr/local to /opt for Apple Silicon. All other systems default to /usr/local as before._
Where search libraries were different (only for macOS), code was added to only add the correct libraries to the appropriate architecture. This eliminates a lot of warning message for missing libraries.
Compiler flags were updated to conform to current clang. …

[Build-System] Update configure.ac for macOS updates
